database:
  host: localhost
  port: 5432
  username: your_username
  password: your_password
  db_name: your_database_name

api:
  key: your_api_key
  endpoint: https://api.example.com

logging:
  level: DEBUG
  file: logs/app.log

model:
  type: bert  # or cnn
  save_path: models/saved_model

training:
  batch_size: 32
  epochs: 10
  learning_rate: 0.001

data:
  train_file: data/train.txt
  test_file: data/test.txt
  preprocess: true